/* Shared label keys for the public DutyEstimator (homepage + /landed-cost).
   Must stay in sync with the `estimator` message namespace. */

export const ESTIMATOR_LABEL_KEYS = [
  "eyebrow",
  "title",
  "sub",
  "importBtn",
  "importHint",
  "importing",
  "importOk",
  "importFail",
  "importNoText",
  "importTooBig",
  "productName",
  "productNamePh",
  "material",
  "materialPh",
  "intendedUse",
  "intendedUsePh",
  "hts",
  "htsPh",
  "origin",
  "originPh",
  "lookup",
  "lookingUp",
  "needInput",
  "pickCandidate",
  "htsTooShort",
  "notFound",
  "compoundNote",
  "lookupFailed",
  "usitcRate",
  "suggestFL",
  "suggest232",
  "capNote",
  "apply",
  "invValue",
  "mfn",
  "rate301orig",
  "rate301fl",
  "rate232",
  "ocean",
  "colItem",
  "colRate",
  "colAmount",
  "rowBase",
  "row301orig",
  "row301fl",
  "row232",
  "rowDutyTotal",
  "rowMpf",
  "rowHmf",
  "rowGrand",
  "mpfFy26",
  "mpfFy27",
  "disclaimer",
  "cta",
] as const;

export function buildEstimatorLabels(
  te: (key: string) => string
): Record<string, string> {
  return Object.fromEntries(ESTIMATOR_LABEL_KEYS.map((k) => [k, te(k)]));
}

/* Flexport-style estimator labels (`fxest` message namespace). */
export const FXEST_LABEL_KEYS = [
  "eyebrow",
  "title",
  "sub",
  "calcTitle",
  "resetForm",
  "importBtn",
  "importHint",
  "importing",
  "importOk",
  "importFail",
  "importNoText",
  "importTooBig",
  "searchLabel",
  "searchPh",
  "clearSearch",
  "lookup",
  "lookingUp",
  "needInput",
  "pickCandidate",
  "notFound",
  "lookupFailed",
  "valueLabel",
  "qtyLabel",
  "qtyPh",
  "qtyHint",
  "originLabel",
  "modeLabel",
  "modeOcean",
  "modeAir",
  "entryDateLabel",
  "exclTitle",
  "exclDonationDesc",
  "applied",
  "notApplied",
  "exclNote",
  "resultsTitle",
  "sendResults",
  "copied",
  "adTitle",
  "adCta",
  "dutyRateLabel",
  "totalDutiesLabel",
  "costTitle",
  "baseCost",
  "hmfRow",
  "mpfRow",
  "landedCost",
  "lineTitle",
  "lineValue",
  "mfnName",
  "flName",
  "c301Name",
  "r232Name",
  "free",
  "disclaimer",
  "disclaimerShort",
  "cta",
] as const;

export function buildFxestLabels(
  tf: (key: string) => string
): Record<string, string> {
  return Object.fromEntries(FXEST_LABEL_KEYS.map((k) => [k, tf(k)]));
}
