/* Shared label keys for the public DutyEstimator (homepage + /landed-cost).
   Must stay in sync with the `estimator` message namespace. */

export const ESTIMATOR_LABEL_KEYS = [
  "eyebrow",
  "title",
  "sub",
  "importBtn",
  "importHint",
  "importing",
  "importOk",
  "importFail",
  "importNoText",
  "importTooBig",
  "productName",
  "productNamePh",
  "material",
  "materialPh",
  "intendedUse",
  "intendedUsePh",
  "hts",
  "htsPh",
  "origin",
  "originPh",
  "lookup",
  "lookingUp",
  "needInput",
  "pickCandidate",
  "htsTooShort",
  "notFound",
  "compoundNote",
  "lookupFailed",
  "usitcRate",
  "suggestFL",
  "suggest232",
  "capNote",
  "apply",
  "invValue",
  "mfn",
  "rate301orig",
  "rate301fl",
  "rate232",
  "ocean",
  "colItem",
  "colRate",
  "colAmount",
  "rowBase",
  "row301orig",
  "row301fl",
  "row232",
  "rowDutyTotal",
  "rowMpf",
  "rowHmf",
  "rowGrand",
  "mpfFy26",
  "mpfFy27",
  "disclaimer",
  "cta",
] as const;

export function buildEstimatorLabels(
  te: (key: string) => string
): Record<string, string> {
  return Object.fromEntries(ESTIMATOR_LABEL_KEYS.map((k) => [k, te(k)]));
}
